<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_terms_and_conditions2</name>
   <tag></tag>
   <elementGuidId>86d1eb20-13d9-4faa-a5bd-0b1ae4f60518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='terms_and_conditions2_i_accept_the_a_href_https_www_intrepidtravel_com_us_booking_intrepid_privacy_target_blank_style_color_00_ab_99_text_decoration_none_privacy_statement_a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#terms_and_conditions2_i_accept_the_a_href_https_www_intrepidtravel_com_us_booking_intrepid_privacy_target_blank_style_color_00_ab_99_text_decoration_none_privacy_statement_a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms_and_conditions2_i_accept_the_a_href_https_www_intrepidtravel_com_us_booking_intrepid_privacy_target_blank_style_color_00_ab_99_text_decoration_none_privacy_statement_a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms_and_conditions2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I accept the &lt;a href=&quot;https://www.intrepidtravel.com/us/booking-intrepid/privacy&quot; target=&quot;_blank&quot; style=&quot;color:#00AB99;text-decoration:none;&quot;>privacy statement&lt;/a></value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox form-builder-checkbox-input form_elem_terms_and_conditions2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms_and_conditions2_i_accept_the_a_href_https_www_intrepidtravel_com_us_booking_intrepid_privacy_target_blank_style_color_00_ab_99_text_decoration_none_privacy_statement_a&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Beautiful Northern Thailand  Intrepid _6e7dbf/iframe__ub-emb-iframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='terms_and_conditions2_i_accept_the_a_href_https_www_intrepidtravel_com_us_booking_intrepid_privacy_target_blank_style_color_00_ab_99_text_decoration_none_privacy_statement_a']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ub-option-terms_and_conditions2-item-0']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
