<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Explorer_imagery--fluid</name>
   <tag></tag>
   <elementGuidId>3782d819-f604-4d8d-a2b2-63fbb7a0203a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div/div[5]/div/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.imagery--fluid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.intrepidtravel.com/sites/intrepid/files/styles/low-quality/public/elements/product/map/TTSN%202020.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://www.intrepidtravel.com/sites/intrepid/files/styles/75w/public/elements/product/map/TTSN%202020.png 75w, https://www.intrepidtravel.com/sites/intrepid/files/styles/160w/public/elements/product/map/TTSN%202020.png 160w, https://www.intrepidtravel.com/sites/intrepid/files/styles/320w/public/elements/product/map/TTSN%202020.png 320w, https://www.intrepidtravel.com/sites/intrepid/files/styles/480w/public/elements/product/map/TTSN%202020.png 480w, https://www.intrepidtravel.com/sites/intrepid/files/styles/640w/public/elements/product/map/TTSN%202020.png 640w, https://www.intrepidtravel.com/sites/intrepid/files/styles/800w/public/elements/product/map/TTSN%202020.png 800w, https://www.intrepidtravel.com/sites/intrepid/files/styles/960w/public/elements/product/map/TTSN%202020.png 960w, https://www.intrepidtravel.com/sites/intrepid/files/styles/1080w/public/elements/product/map/TTSN%202020.png 1080w, https://www.intrepidtravel.com/sites/intrepid/files/styles/1240w/public/elements/product/map/TTSN%202020.png 1240w, https://www.intrepidtravel.com/sites/intrepid/files/styles/1400w/public/elements/product/map/TTSN%202020.png 1400w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2200</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1470</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Map of Beautiful Northern Thailand including Thailand</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imagery--fluid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>342px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.intrepidtravel.com/sites/intrepid/files/styles/low-quality/public/elements/product/map/TTSN%202020.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://www.intrepidtravel.com/sites/intrepid/files/styles/75w/public/elements/product/map/TTSN%202020.png 75w, https://www.intrepidtravel.com/sites/intrepid/files/styles/160w/public/elements/product/map/TTSN%202020.png 160w, https://www.intrepidtravel.com/sites/intrepid/files/styles/320w/public/elements/product/map/TTSN%202020.png 320w, https://www.intrepidtravel.com/sites/intrepid/files/styles/480w/public/elements/product/map/TTSN%202020.png 480w, https://www.intrepidtravel.com/sites/intrepid/files/styles/640w/public/elements/product/map/TTSN%202020.png 640w, https://www.intrepidtravel.com/sites/intrepid/files/styles/800w/public/elements/product/map/TTSN%202020.png 800w, https://www.intrepidtravel.com/sites/intrepid/files/styles/960w/public/elements/product/map/TTSN%202020.png 960w, https://www.intrepidtravel.com/sites/intrepid/files/styles/1080w/public/elements/product/map/TTSN%202020.png 1080w, https://www.intrepidtravel.com/sites/intrepid/files/styles/1240w/public/elements/product/map/TTSN%202020.png 1240w, https://www.intrepidtravel.com/sites/intrepid/files/styles/1400w/public/elements/product/map/TTSN%202020.png 1400w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--9-col l-grid__cell--12-col-tablet l-grid__cell--12-col-phone&quot;]/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--12-col l-grid__cell--6-col-desktop l-grid__cell--4-col-tablet&quot;]/div[@class=&quot;card&quot;]/a[@class=&quot;card__content card__content--link&quot;]/div[@class=&quot;card__image&quot;]/img[@class=&quot;imagery--fluid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div/div[5]/div/div/div/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Map of Beautiful Northern Thailand including Thailand']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
   </webElementXpaths>
</WebElementEntity>
